AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pruebatecnica-intermedio8

  Sample SAM Template for pruebatecnica-intermedio8
  

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x   # 👈 añade esto
    Architectures:
      - x86_64
Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: todos
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getTodos.handler
      CodeUri: src/handlers/
      Policies:
        - DynamoDBReadPolicy:
            TableName: todos
      Events:
        GetTodosEvent:
          Type: Api
          Properties:
            Path: /todos
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - getTodos.ts

  UpdateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateTodo.handler
      CodeUri: src/handlers/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: todos
      Events:
        UpdateTodoEvent:
          Type: Api
          Properties:
            Path: /todos/{id}
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - updateTodo.ts



Outputs:
  ApiBaseUrl:
    Description: "Base URL de la API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
